// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ScryFallMagic.Data;

#nullable disable

namespace ScryFallMagic.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20230202105740_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

             modelBuilder.Entity("ScryFallManager.Entities.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColecaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CustoMana")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Idioma")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Raridade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Texto")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ColecaoId");

                    b.ToTable("Cartas");
                });

            modelBuilder.Entity("ScryFallManager.Entities.Colecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Idioma")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Colecao");
                });

            modelBuilder.Entity("ScryFallManager.Entities.Versao", b =>
                {
                    b.Property<int>("VersaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersaoId"));

                    b.Property<DateTime>("DataLancamento")
                        .HasMaxLength(20)
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("VersaoId");

                    b.ToTable("Versoes");
                });

            modelBuilder.Entity("ScryFallManager.Entities.Carta", b =>
                {
                    b.HasOne("ScryFallManager.Entities.Colecao", "Colecao")
                        .WithMany("Cartas")
                        .HasForeignKey("ColecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScryFallManager.Entities.Versao", "Versao")
                        .WithMany("Cartas")
                        .HasForeignKey("VersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colecao");

                    b.Navigation("Versao");
                });


            modelBuilder.Entity("ScryFallManager.Entities.Colecao", b =>
                {
                    b.Navigation("Cartas");
                });

            modelBuilder.Entity("ScryFallManager.Entities.Versao", b =>
                {
                    b.Navigation("Cartas");
                });
#pragma warning restore 612, 618
        }
    }
}